"""Initial tables: upload_sessions, transcode_jobs, assets

Revision ID: 1cc06cdfeafe
Revises: 
Create Date: 2026-09-06 20:26:06.759119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cc06cdfeafe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('total_bytes', sa.Integer(), nullable=False),
    sa.Column('offset_bytes', sa.Integer(), nullable=False),
    sa.Column('staging_path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('callback_url', sa.String(length=1024), nullable=True),
    sa.Column('caller_reference', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_sessions_owner_user_id'), 'upload_sessions', ['owner_user_id'], unique=False)
    op.create_table('transcode_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upload_session_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('source_duration_seconds', sa.Float(), nullable=True),
    sa.Column('source_width', sa.Integer(), nullable=True),
    sa.Column('source_height', sa.Integer(), nullable=True),
    sa.Column('callback_url', sa.String(length=1024), nullable=True),
    sa.Column('caller_reference', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['upload_session_id'], ['upload_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcode_jobs_status'), 'transcode_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_transcode_jobs_upload_session_id'), 'transcode_jobs', ['upload_session_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transcode_job_id', sa.String(length=36), nullable=False),
    sa.Column('master_playlist_url', sa.String(length=1024), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('renditions', sa.JSON(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transcode_job_id'], ['transcode_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcode_job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assets')
    op.drop_index(op.f('ix_transcode_jobs_upload_session_id'), table_name='transcode_jobs')
    op.drop_index(op.f('ix_transcode_jobs_status'), table_name='transcode_jobs')
    op.drop_table('transcode_jobs')
    op.drop_index(op.f('ix_upload_sessions_owner_user_id'), table_name='upload_sessions')
    op.drop_table('upload_sessions')
    # ### end Alembic commands ###
